<?php
?>
<script src="js/alerta.js" type="text/javascript"></script>
<div  class="container" style="padding-top:80px;">
    <div class="page-header">
        <h1>Alarmas</h1>
        <form id="alerta" name="alerta" method="post" id="formu" action="?sec=configuracion&ssec=alarma&do=add" class="form-inline well pull-right" style="padding: 10px 19px;margin-top: -10px;">
            <label for="nom">Nueva alarma: </label><input id="nom" name="nom" value="" class="span3 required" style="margin: 0 5px;"/><input type="submit" value="Guardar" class="btn btn-primary"/>
        </form>
    </div>
    <div class="bloque">
        <? if(count($cp->getCSec()->getCSec()->alertas)>0) { ?>
        <table class="table table-striped table-bordered" id="lista">
            <thead>
                <tr>
                    <th class="red">Nombre</th>
                    <th class="actionCol">Acci&oacute;n</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($cp->getCSec()->getCSec()->alertas as $a) {?>
                <tr <?=(!$a->ESTADO_ALERTA)?"class='deleted'":""?>>
                    <td><?= $a->NOM_ALERTA; ?></td>
                    <td class="actionCol">
                        <a href="?sec=configuracion&ssec=alarma&op=mod&id=<?=$a->ID_ALERTA;?>" class="tp" title="Editar"><i class="icon-edit"></i></a>
                        <a href="?sec=configuracion&ssec=alarma&do=del&id=<?=$a->ID_ALERTA;?>" class="tp" title="Eliminar"><i class="icon-remove"></i></a>
                    </td>
                </tr>
                <? } ?>
            </tbody>
        </table>
        <? } else { ?>
            <p class="mensaje">No hay Alarmas</p>
        <? } ?>
    </div>
</div>