<?php
?>
<script src="js/alerta.js" type="text/javascript"></script>
<div class="center_content">
    <h1>Alarmas</h1>
    <div class="bloque">
<!--        <h2>Todas</h2>-->
        <form id="alerta" name="alerta" method="post" id="formu" action="?sec=configuracion&ssec=alarma&do=add" class="inline">
            <label for="nom">Nueva alarma: </label><input id="nom" name="nom" value="" class="span3 required" style="margin-right: 5px;"/><input type="submit" value="Guardar" class="btn danger"/>
        </form>
        <? if(count($cp->getCSec()->getCSec()->alertas)>0) { ?>
        <table class="zebra-striped" id="lista">
            <thead>
                <tr>
                    <th class="red">Nombre</th>
                    <th class="actionCol">Editar</th>
                    <th class="actionCol">Eliminar</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($cp->getCSec()->getCSec()->alertas as $a) {?>
                <tr <?=(!$a->ESTADO_ALERTA)?"class='deleted'":""?>>
                    <td><?= $a->NOM_ALERTA; ?></td>
                    <td class="actionCol"><a href="?sec=configuracion&ssec=alarma&op=mod&id=<?=$a->ID_ALERTA;?>"><img src="img/page_edit.png" border="0" /></a></td>
                    <td class="actionCol"><a href="?sec=configuracion&ssec=alarma&do=del&id=<?=$a->ID_ALERTA;?>"><img src="img/delete.png" border="0" /></a></td>
                </tr>
                <? } ?>
            </tbody>
        </table>
        <? } else { ?>
            <p class="mensaje">No hay Alarmas</p>
        <? } ?>
    </div>
</div>