<?php
function getSelect($obj, $val, $id, $nom, $sel = null, $style=null, $onChange=null, $ninguno = false) {
    $r = "<SELECT name='$nom' class='medium-input' style='$style' onChange=\"" . $onChange . "\" id='$nom'>";
    if($ninguno)
        $r .= "<OPTION value = '0'>Ninguno</OPTION>";
    else 
        $r .= "<OPTION value = '-1' DISABLED>Selecciona</OPTION>";
    foreach ($obj as $o) {
        if ($sel == $o->$id) {
            $r .= "<OPTION value='" . $o->$id . "' SELECTED>" . $o->$val . "</OPTION>";
        } else {
            $r .= "<OPTION value='" . $o->$id . "'>" . $o->$val . "</OPTION>";
        }
    }
    $r .= "</SELECT>";
    return $r;
}
?>
<script src="js/usuario.js" type="text/javascript"></script>
<div  class="container" style="padding-top:80px;">
    <div class="page-header">
        <h1>Conductores</h1>
        <a href="?sec=configuracion&ssec=conductor&op=add" class="btn pull-right"><i class="icon-plus"></i>Agregar Conductor</a>
    </div>
    <div class="bloque">
        <? if(count($cp->getCSec()->getCSec()->usuarios)>0) { ?>
        <table class="table table-striped table-bordered" id="lista">
            <thead>
                <tr>
                    <th class="red">Nombre</th>
                    <th class="red">Rut</th>
                    <th class="red">Telefono</th>
                    <th class="actionCol">Acci&oacute;n</th>
                </tr>
            </thead>
            <tbody>
                <? foreach($cp->getCSec()->getCSec()->usuarios as $a) {?>
                <tr <?=(!$a->isActive)?"class='deleted'":""?>>
                    <td><?= $a->displayName; ?></td>
                    <td><?= $a->rut; ?></td>
                    <td><?= $a->contactPhone; ?></td>
                    <td class="actionCol">
                        <a href="?sec=configuracion&ssec=conductor&op=mod&id=<?=$a->driverID;?>" class="tp" title="Editar"><i class="icon-edit"></i></a>
                        <a href="?sec=configuracion&ssec=conductor&do=del&id=<?=$a->driverID;?>" class="tp" title="Eliminar"><i class="icon-remove"></i></a>
                    </td>
                </tr>
                <? } ?>
            </tbody>
        </table>
        <? } else { ?>
         <p class="mensaje">No hay Conductores</p>
        <? } ?>
    </div>
</div>
<!--<div class="modal fade" id="add">
    <div class="modal-header">
        <a href="#" class="close" data-dismiss="modal">×</a>
        <h3>Nuevo conductor</h3>
    </div>
    <form action="?sec=configuracion&ssec=conductor&do=<?=$cp->getCSec()->getCSec()->op?>" method="post" name="formu" id="formu" class="form-horizontal" style="margin: 0;">
    <div class="modal-body">
            <div class="control-group">
                <label>Nombre:</label>
                <div class="controls">
                <input class="text-input medium-input required" type="text" name="nom" value="<?=($cp->getCSec()->getCSec()->obj!=null)?$cp->getCSec()->getCSec()->obj->displayName:""?>" />
                <input type="hidden" name="id" value="<?=($cp->getCSec()->getCSec()->obj!=null)?$cp->getCSec()->getCSec()->obj->driverID:""?>" id="id"/>
                <input type="hidden" name="accountID" value="<?=$cp->getSession()->get("accountID")?>"/>
                </div>
            </div>
            <div class="control-group">
                <label>RUT:</label>
                <div class="controls">
                <input class="text-input medium-input required" type="text" name="rut" value="<?=($cp->getCSec()->getCSec()->obj!=null)?$cp->getCSec()->getCSec()->obj->rut:""?>"/>
                </div>
            </div>
            <div class="control-group">
                <label>Tel&eacute;fono:</label>
                <div class="controls">
                <input class="text-input medium-input required" type="text" name="tel" value="<?=($cp->getCSec()->getCSec()->obj!=null)?$cp->getCSec()->getCSec()->obj->contactPhone:""?>"/>
                </div>
            </div>
            <div class="control-group">
                <label>Veh&iacute;culo:</label>
                <div class="controls">
                <?=getSelect($cp->getCSec()->getCSec()->vehiculos, "displayName", "deviceID", "vehiculo", ($cp->getCSec()->getCSec()->dev!=null)?$cp->getCSec()->getCSec()->dev->deviceID:null, null, null, true);?>
                </div>
            </div>
            <div class="control-group">
                <label>Estado:</label>
                <div class="controls">
                <?=getSelect($cp->getCSec()->getCSec()->estados, "estado", "id", "estado", ($cp->getCSec()->getCSec()->obj!=null)?$cp->getCSec()->getCSec()->obj->isActive:"");?>
                    </div>
            </div>
    </div>
    <div class="modal-footer">
        <input class="btn btn-primary" type="submit" value="Guardar" />
    </div>
    </form>
</div>-->