<?php ?>
<script src="js/geozona.js" type="text/javascript"></script>
<div class="center_content">
    <h1>Geo Zona</h1>
    <div id="local-nav"><a href="?sec=configuracion&ssec=geozona&op=add" class="btn"><img src="img/add.png" border="0"/>Agregar Geo zona</a></div>
    <div class="bloque">
<!--        <h2>Todos</h2>-->
        <? if(count($cp->getCSec()->getCSec()->poligonos)>0) { ?>
        <table class="zebra-striped" id="lista">
            <thead>
                <tr>
                    <th class="actionCol">Tipo</th>
                    <th class="red">Nombre</th>
                    <th class="actionCol">Editar</th>
                    <th class="actionCol">Eliminar</th>
                </tr>
            </thead>
            <tbody>
            <? foreach ($cp->getCSec()->getCSec()->poligonos as $p) { ?>
                <tr <?=(!$p->ESTADO_POLIGONO)?"class='deleted'":""?>>
                    <td class="actionCol"><img src="http://google.com/mapfiles/ms/t/<?= ($p->ID_TIPO_POLIGONO == 1) ? "Blu" : "Bpu"; ?>.png" border="0" width="20" title="<?= ($p->ID_TIPO_POLIGONO == 1) ? "Geo frontera" : "Geo zona"; ?>"/></td>
                    <td><?= $p->NOM_POLIGONO; ?></td>
                    <td class="actionCol"><a href="?sec=configuracion&ssec=geozona&op=mod&id=<?= $p->ID_POLIGONO; ?>"><img src="img/page_edit.png" border="0" /></a></td>
                    <td class="actionCol"><a href="?sec=configuracion&ssec=geozona&do=del&id=<?= $p->ID_POLIGONO; ?>"><img src="img/delete.png" border="0" /></a></td>
                </tr>
            <? } ?>
            <tbody>
        </table>
        <? } else {?>
        <p class="mensaje">No hay Geozonas</p>
        <? } ?>
    </div>
</div>

