<?php ?>
<script src="js/geozona.js" type="text/javascript"></script>
<div  class="container" style="padding-top:80px;">
    <div class="page-header">
        <h1>Geo Zona</h1>
        <a href="?sec=configuracion&ssec=geozona&op=add" class="btn pull-right"><i class="icon-plus"></i>Agregar Geo zona</a>
    </div>
    <div class="bloque">
<!--        <h2>Todos</h2>-->
        <? if(count($cp->getCSec()->getCSec()->poligonos)>0) { ?>
        <table class="table table-striped table-condensed" id="lista">
            <thead>
                <tr>
                    <th class="actionCol">Tipo</th>
                    <th class="red">Nombre</th>
                    <th class="actionCol">Acci&oacute;n</th>
                </tr>
            </thead>
            <tbody>
            <? foreach ($cp->getCSec()->getCSec()->poligonos as $p) { ?>
                <tr <?=(!$p->ESTADO_POLIGONO)?"class='deleted'":""?>>
                    <td class="actionCol"><img src="http://google.com/mapfiles/ms/t/<?= ($p->ID_TIPO_POLIGONO == 1) ? "Blu" : "Bpu"; ?>.png" border="0" width="20" title="<?= ($p->ID_TIPO_POLIGONO == 1) ? "Geo frontera" : "Geo zona"; ?>"/></td>
                    <td><?= $p->NOM_POLIGONO; ?></td>
                    <td class="actionCol">
                        <a href="?sec=configuracion&ssec=geozona&op=mod&id=<?= $p->ID_POLIGONO; ?>" class="tp" title="Editar"><i class="icon-edit"></i></a>
                        <a href="?sec=configuracion&ssec=geozona&do=del&id=<?= $p->ID_POLIGONO; ?>" class="tp" title="Eliminar"><i class="icon-remove"></i></a>
                    </td>
                </tr>
            <? } ?>
            <tbody>
        </table>
        <? } else {?>
        <p class="mensaje">No hay Geozonas</p>
        <? } ?>
    </div>
</div>

