<?
//print_r($cp->poligono);
//print_r($cp->puntos);
//echo $_SERVER["REMOTE_ADDR"]."<br>";
function getSelect($obj, $val, $id, $nom, $sel = null, $style=null, $onChange=null) {
    $r = "<SELECT name='$nom' style='$style' onChange=\"" . $onChange . "\" id='$nom' class='span2'>";
    $r .= "<OPTION value = '-1' DISABLED>Seleccionar...</OPTION>";
    foreach ($obj as $o) {
        if ($sel == $o->$id) {
            $r .= "<OPTION value='" . $o->$id . "' SELECTED>" . $o->$val . "</OPTION>";
        } else {
            $r .= "<OPTION value='" . $o->$id . "'>" . $o->$val . "</OPTION>";
        }
    }
    $r .= "</SELECT>";
    return $r;
}
$error = array("Los cambios fueron guardados correctamente", "Los cambios NO pudieron ser guardados");
if(isset($_GET["e"])) {
    $msg = "<div>".$error[$_GET["e"]]."</div>";
    if($_GET["e"]>0) {
        $tipoMsg = "error";
    } else {
        $tipoMsg = "success";
    }
} else {
    if($cp->getCSec()->getCSec()->op == "add") {
        $msg = "<p>Complete los siguientes campos</p>";
        $tipoMsg = "info";
    } else {
        $msg = "<p>Edite los campos que quiera modificar</p>";
        $tipoMsg = "info";
    }
}
?>
<link rel="stylesheet" type="text/css" href="css/geozona.css" />
<script src="js/polygonEdit_packed.js" type="text/javascript"></script>
<script src="js/polylineEdit_packed.js" type="text/javascript"></script>
<script src="js/geozona_mod_v3.js" type="text/javascript"></script>
<div  class="container" style="padding-top:80px;">
    <div class="page-header">
        <h1>Geo Zona</h1>
        <a href="?sec=configuracion&ssec=geozona" class="btn pull-right"><i class="icon-arrow-left"></i>Volver</a>
    </div>
    <h2><?= $cp->getCSec()->getCSec()->tilSec; ?></h2>
    <div class="well">
    <div id="geo-main">
        <? if($cp->getCSec()->getCSec()->op == "add") {?>
        <div id="menugeo">
            <ul>
                <li><a href="#" onClick="stopEditing(); return false;"><img src="http://google.com/mapfiles/ms/t/Bsu.png" border="0" id="Bs"/></a></li>
                <li><a href="#" onClick="startLine(); return false;"><img src="http://google.com/mapfiles/ms/t/Blu.png" border="0" id="Bl"/></a></li>
                <li><a href="#" onClick="startShape(); return false;"><img src="http://google.com/mapfiles/ms/t/Bpu.png" border="0" id="Bp"/></a></li>
            </ul>
        </div>
        <? } ?>
        <form name="poly" method="post" action="?sec=configuracion&ssec=geozona&do=<?=$cp->getCSec()->getCSec()->op;?>" id="formu" class="form-inline pull-right">
<!--            <div id="msg" class="alert-message <? echo $tipoMsg; ?>"><? echo $msg; ?></div>-->
            <label>Nombre: </label>
            <input class="span2 required" type="text" name="nom" value="<?=$cp->getCSec()->getCSec()->poligono->NOM_POLIGONO;?>"/>
<!--            <label>Estado:</label>-->
            <?//=getSelect($cp->getCSec()->getCSec()->estados, "estado", "id", "estado", ($cp->getCSec()->getCSec()->poligono!=null)?$cp->getCSec()->getCSec()->poligono->ESTADO_POLIGONO:null);?>
            <input class="btn btn-primary" type="submit" value="Guardar" />
            <input type="hidden" name="accountID" value="<?=$cp->getSession()->get("accountID");?>"/>
            <input type="hidden" name="userID" value="<?=$cp->getSession()->get("userID")?>"/>
            <input type="hidden" name="tipo" value="<?=$cp->getCSec()->getCSec()->poligono->ID_TIPO_POLIGONO;?>"/>
            <input type="hidden" name="idPol" value="<?=$cp->getCSec()->getCSec()->poligono->ID_POLIGONO;?>"/>
            <input type="hidden" name="nPuntos" value="<?=count($cp->getCSec()->getCSec()->puntos);?>"/>
            <input type="hidden" name="estado" value="1"/>
            <?
                if($cp->getCSec()->getCSec()->puntos!=null) {
                    $nPuntos = count($cp->getCSec()->getCSec()->puntos);
                    for($i=0; $i<$nPuntos; $i++) {
                        $p = $cp->getCSec()->getCSec()->puntos[$i];
                        ?>
                    <input type="hidden" name="p_<?=$i;?>" value="<?=$p->LAT_PUNTO?>,<?=$p->LON_PUNTO?>">
            <?      }
                }
            ?>
        </form>
        <div id="map"></div>
    </div>
    </div>
</div>