<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>GPSLine :: Configuracion </title>
        <link rel="Shortcut Icon" href="../favicon.ico"/>
        <script src="js/jquery-1.5.min.js" type="text/javascript"></script>
        <script src="js/jquery.validate.js" type="text/javascript"></script>
        <script src="js/jquery.dataTables.min.js" type="text/javascript"></script>
        <!--<link type="text/css" href="themes/smoothness/jquery-ui-1.8.4.custom.css" rel="stylesheet" />-->
        <!--<link type="text/css" href="5/css/gpsrojo-theme/jquery-ui-1.8.5.custom.css" rel="stylesheet" />-->
        <script src="js/alerta.js" type="text/javascript"></script>
        <link rel="stylesheet" type="text/css" href="css/style.css" />
        <!--<link href="css/demo_table.css" rel="stylesheet" type="text/css" />-->
        <!--<link href="css/demo_table_jui.css" rel="stylesheet" type="text/css" />-->
    </head>
    <body>
        <div id="main_container">
            <div id="header">
                <div class="logo"><img src="img/logo.png" border="0" alt="" title="" /></div>
            </div>
            <div class="menu">
                <ul>
                    <li <?= ($cp->sec == "usuario") ? " class='selected'" : ""; ?>><a href="?sec=usuario">Usuario</a></li>
                    <li <?= ($cp->sec == "vehiculo") ? " class='selected'" : ""; ?>><a href="?sec=vehiculo">Vehiculo</a></li>
                    <li <?= ($cp->sec == "alerta") ? " class='selected'" : ""; ?>><a href="?sec=alerta">Alertas</a></li>
                    <li <?= ($cp->sec == "ptointeres") ? " class='selected'" : ""; ?>><a href="#">Pts. de Interes</a></li>
                    <li <?= ($cp->sec == "geozona") ? " class='selected'" : ""; ?>><a href="?sec=geozona">Geo Zona</a></li>
                </ul>
                <ul class="sesion">
                    <li>Identificado como:</li>
                    <li><?= $cp->getSession()->get("emp") ?> | <?= $cp->getSession()->get("usuario") ?></li>
                </ul>
            </div>
            <? include $cp->getCSec()->getLayout(); ?>
            <div id="footer">
                <div class="left_footer">GPSLINE / San Juan #4693, San Joaqu&iacute;n - Santiago - Chile / Tel&eacute;fono (+56 2) 424 78 80 <br />&copy; 2010 GPSLINE - Reservados todos los derechos / Desarrollo: NETMARKET</div>
            </div>
        </div>
    </body>
</html>

