<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no" /> 
        <title>GPSLine | <?=$cp->getSession()->get("accountName")?></title>
        <link rel="Shortcut Icon" href="favicon.ico"/>
        <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=true"></script>
        <script type="text/javascript" src="http://google-maps-utility-library-v3.googlecode.com/svn/tags/markermanager/1.0/src/markermanager.js"></script>
        <script type="text/javascript" src="http://google-maps-utility-library-v3.googlecode.com/svn/trunk/markerclusterer/src/markerclusterer.js"></script>
        <script src="js/jquery-1.5.1.min.js" type="text/javascript"></script>
        <script type="text/javascript" src="js/ui/jquery.ui.core.js"></script>
        <script type="text/javascript" src="js/ui/jquery.ui.widget.js"></script>
        <script type="text/javascript" src="js/ui/jquery.ui.mouse.js"></script>
        <script type="text/javascript" src="js/ui/jquery.ui.draggable.js"></script>
        <script src="js/jquery.url.js" type="text/javascript"></script>
        <script src="js/menuGMap.js" type="text/javascript"></script>
        <script src="js/jquery.validate.js" type="text/javascript"></script>
        <script src="js/jquery.dataTables.min.js" type="text/javascript"></script>
        <script src="js/jquery.jgrowl_compressed.js" type="text/javascript"></script>
        <script src="js/jquery.titleBlink.js" type="text/javascript"></script>
        <script src="js/jquery.qtip-1.0.0-rc3.min.js" type="text/javascript"></script>
        <script type="text/javascript" src="js/ui/jquery.ui.core.js"></script>
        <script type="text/javascript" src="js/ui/jquery.ui.widget.js"></script>
        <script type="text/javascript" src="js/ui/jquery.ui.datepicker.js"></script>
        <script type="text/javascript" src="js/ui/i18n/jquery.ui.datepicker-es.js"></script>
        <script type="text/javascript" src="js/ui/jquery-ui-1.8.4.custom.js"></script>
        <script type="text/javascript" src="js/jquery.tmpl.min.js"></script>
        <script type="text/javascript" src="js/jquery.infieldlabel.min.js"></script>
        <script type="text/javascript" src="js/highcharts.js"></script>
        <script type="text/javascript" src="js/list.js"></script>
        <script type="text/javascript" src="/js/jquery.jplayer.min.js"></script>
        <script src="js/jquery.tablesorter.min.js"></script>
        <script src="js/mon_alarma.js" type="text/javascript"></script>
        <script src="js/main.js" type="text/javascript"></script>
        <link rel="stylesheet" type="text/css" href="css/reset.css" />
        <link rel="stylesheet" type="text/css" href="css/bootstrap.css" />
        <link rel="stylesheet" type="text/css" href="css/jquery.jgrowl.css" />
        <link rel="stylesheet" type="text/css" href="css/jquery.qtip.min.css" />
        <link rel="stylesheet" type="text/css" href="css/style-ie.css" />
        <link rel="stylesheet" type="text/css" href="css/new.css" />
        <script type="text/javascript">
          var _gaq = _gaq || [];
          _gaq.push(['_setAccount', 'UA-22276420-1']);
          _gaq.push(['_setDomainName', '.gpsline.cl']);
          _gaq.push(['_trackPageview']);

          (function() {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
          })();
        </script>
    </head>
    <body>
        <div id="alarmaSound"></div>
        <div id="page-wrap">
            <div id="inside">
                <div id="header">
                    <div class="logo"><a href="http://www.gpsline.cl" target="_blank"><img src="img/logo2.png" border="0" alt="" title=""/></a></div>
                    <div id="user-info">
                        <span id="name"><?= $cp->getSession()->get("user"); ?></span>
                        <div class="dropdown">
                            <ul class="unstyled">
                                <li><a href="?sec=log&do=out">Cerrar sesi&oacute;n</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="top-nav">
                        <ul id="main-nav">
                            <li <?= ($cp->sec == "monitoreo") ? " class='active'" : ""; ?>><a href="?sec=monitoreo">Monitoreo</a></li>
                            <li <?= ($cp->sec == "reporte") ? " class='active'" : ""; ?>><a href="#">Reportes</a>
                                <ul class="dropdown">
                                    <li><a href="/#/reporte/auditoria" onClick="setReporte(0);">Auditoria</a></li>
                                    <li><a href="/#/reporte/alarma" onClick="setReporte(1);">Alarmas</a></li>
                                    <li><a href="/#/reporte/recorrido" onClick="setReporte(2);">Km. Recorridos</a></li>
                                    <li><a href="/#/reporte/velocidad" onClick="setReporte(3);">Velocidad</a></li>
                                    <li><a href="/#/reporte/consumo" onClick="setReporte(4);">Consumo</a></li>
                                </ul>
                            </li>
                            <? if($cp->isAdmin() || $cp->isSuperAdmin()) { ?>
                            <li <?= ($cp->sec == "configuracion") ? " class='active'" : ""; ?>><a href="?sec=configuracion">Configuraci&oacute;n</a>
                                <ul class="dropdown">
                                    <li><a href="?sec=configuracion&ssec=vehiculo">Veh&iacute;culos</a></li>
                                    <li><a href="?sec=configuracion&ssec=conductor">Conductores</a></li>
                                    <li><a href="?sec=configuracion&ssec=usuario">Usuarios</a></li>
                                    <li><a href="?sec=configuracion&ssec=alarma">Alarmas</a></li>
                                    <li><a href="?sec=configuracion&ssec=puntointeres">Ptos. Interes</a></li>
                                    <li><a href="?sec=configuracion&ssec=geozona">Geo Zona</a></li>
                                </ul>
                            </li>
                            <? } ?>
                        </ul>
                    </div>
                    <div style="clear: both;"></div>
                </div>
                <? if($cp->sec == "monitoreo") { ?>
                <div id="right-sidebar">
                    <div id="bar">
                        <h1>&Uacute;ltimos movimientos</h1>
                        <div class="scroll">
                        <ul id="alarma"></ul>
                        </div>
                    </div>
                    <div id="toggle-right">><br />></div>
                </div>
                <? } ?>
                <div id="left-sidebar" <?php echo ($cp->sec == "monitoreo")?"style='background: url(../img/tx_1.jpg);'":""?>>
<!--                    <div id="logo"></div>-->
                    <? if($cp->sec == "monitoreo") { ?>
                    <div id="toggle-left"><<br /><</div>
                    <? } ?>
                    <div id="bar">
                    <? if($cp->sec == "configuracion") { ?>
                        <h1>Configuraci&oacute;n</h1>
                        <ul class="side-nav">
                            <li <?= ($cp->getCSec()->sec == "vehiculo") ? " class='active'" : ""; ?>><a href="?sec=configuracion&ssec=vehiculo">Veh&iacute;culos</a></li>
                            <li <?= ($cp->getCSec()->sec == "conductor") ? " class='active'" : ""; ?>><a href="?sec=configuracion&ssec=conductor">Conductores</a></li>
                            <li <?= ($cp->getCSec()->sec == "usuario") ? " class='active'" : ""; ?>><a href="?sec=configuracion&ssec=usuario">Usuarios</a></li>
                            <li <?= ($cp->getCSec()->sec == "alarma") ? " class='active'" : ""; ?>><a href="?sec=configuracion&ssec=alarma">Alarmas</a></li>
                            <li <?= ($cp->getCSec()->sec == "puntointeres") ? " class='active'" : ""; ?>><a href="?sec=configuracion&ssec=puntointeres">Puntos de Inter&eacute;s</a></li>
                            <li <?= ($cp->getCSec()->sec == "geozona") ? " class='active'" : ""; ?>><a href="?sec=configuracion&ssec=geozona">Geo Zona</a></li>
                        </ul>
                    <? } elseif($cp->sec == "monitoreo") { ?>
                        <div class="mon_botonera">
                            <a id="btn_pint" class="checkbox" onClick="showPInteres(); return false;" title="Mostrar puntos de interes"><img src="img/marker.png" height="20"/></a>
                            <a id="btn_buscar" class="checkbox" title="Buscar direcci&oacute;n"><img src="img/search.png" height="20"/></a>
                        </div>
                        <h1>Veh&iacute;culos</h1>
                        <div id="devices">
<!--                            <label for="devFiltro">Buscar veh&iacute;culo</label><input class="search" id="devFiltro"/>-->
                            <form id="devFiltro">
                                <p><label for="sDev">Buscar veh&iacute;culo</label>
                                <input type="text" class="search" name="sDev" value="" id="sDev" autocomplete="off"/></p>
                            </form>
                            <div class="scroll">
                                <ul class="grupo">
                                    <? foreach($cp->getCSec()->grupos as $g) { ?>
                                        <li><a href="#" class="nomGrupo"><span id="estado"><img src="img/collapse.png" border="0" class="imgEstado"/> </span><span><?=$g->displayName?></span></a>
                                            <div id="info">
                                                <? foreach($cp->getCSec()->sensor as $s) { ?>
                                                <? if($s->IN_TABLA == 1) { ?>
                                                <span title="<?=$s->NOM_SENSOR?>"><?=$s->ABR_SENSOR?></span>
                                                <? } ?>
                                                <? } ?>
                                                <span title="Velocidad">Vel</span>
                                            </div>
                                            <ul class="device list">
                                                <? $dev = $cp->getCSec()->getDeviceByGrupo($g->groupID) ?>
                                                <? foreach($dev as $d) { ?>
                                                    <li class="dev_<?=$d->deviceID?>"><a onmousedown="javascript:setActive('<?=$d->deviceID?>'); return false" class="nomDevice"><?=$d->displayName?></a><span id="estado"></span>
                                                        <div id="info">
                                                            <? foreach($cp->getCSec()->sensor as $s) { ?>
                                                            <? if($s->IN_TABLA == 1) { ?>
                                                            <span id="S<?=$s->ID_SENSOR?>">
                                                                <img src='img/no_sensor.png' width='14' alt='No disponible' title='No instalado'/>
                                                            </span>
                                                            <? } ?>
                                                            <? } ?>
                                                            <span id="velocidad">0</span>
                                                        </div>
                                                        <div class="clear"></div>
                                                    </li>
                                                <? } ?>
                                            </ul>
                                        </li>
                                    <? } ?>
                                </ul>
                            </div>
                        </div>
                        <div id="active_dev" style="display:none;" class="nivel_10">
                            <ul class="unstyled">
                                <li id="titulo"></li>
                                <li id="conductor"></li>
                                <li id="patente"></li>
                                <li id="velocidad"></li>
                                <? foreach($cp->getCSec()->sensor as $s) { ?>
                                <? if($s->IN_DETALLE == 1) { ?>
                                <li id="S<?=$s->ID_SENSOR?>"></li>
                                <? } ?>
                                <? } ?>
                                <li id="direccion"></li>
                                <li id="fecha"></li>
                            </ul>
                        </div>
                        <div id="tooltip" style="display:none;"></div>
                    <? } elseif($cp->sec == "reporte") {?>
                        <div class="mon_botonera">
                            <a id="btn_pint" class="checkbox tooltip" onClick="showPInteres(); return false;" title="Descargar reporte"><img src="img/save.png" height="20"/></a>
                            <a id="btn_pint" class="checkbox tooltip" onClick="showPInteres(); return false;" title="Imprimir reporte"><img src="img/print.png" height="20"/></a>
                        </div>
                        <h1>Reportes</h1>
                        <ul class="side-nav">
                            <li <?= ($cp->getCSec()->sec == "auditoria") ? " class='active'" : ""; ?>><a href="?sec=reporte&ssec=auditoria">Auditor&iacute;a</a></li>
                            <li <?= ($cp->getCSec()->sec == "alarma") ? " class='active'" : ""; ?>><a href="?sec=reporte&ssec=alarma">Alarmas</a></li>
<!--                            <li <?= ($cp->getCSec()->sec == "detencion") ? " class='active'" : ""; ?>><a href="?sec=reporte&ssec=detencion">Detenciones</a></li>-->
                            <li <?= ($cp->getCSec()->sec == "recorrido") ? " class='active'" : ""; ?>><a href="?sec=reporte&ssec=recorrido">Kilometros recorridos</a></li>
<!--                            <li <?= ($cp->getCSec()->sec == "sensor") ? " class='active'" : ""; ?>><a href="?sec=reporte&ssec=sensor">Sensores</a></li>-->
                            <li <?= ($cp->getCSec()->sec == "velocidad") ? " class='active'" : ""; ?>><a href="?sec=reporte&ssec=velocidad">Velocidad</a></li>
                        </ul>
                    <? } ?>
                    </div>
                    <? if($cp->sec != "configuracion") { ?>
                    <div id="resize"></div>
                    <? } ?>
                </div>
                <div id="main-content">
                    <? include $cp->getCSec()->getLayout(); ?>
                </div>
                <div style="clear: both;"></div>
<!--                <div id="footer">
                    <p>GPSLINE / San Juan #4693, San Joaqu&iacute;n - Santiago - Chile / Tel&eacute;fono (+56 2) 424 78 80 <br />&copy; 2010 GPSLINE - Reservados todos los derechos / Desarrollo: NETMARKET</p>
                </div>-->
            </div>
            <div style="clear: both;"></div>
        </div>
    </body>
</html>