<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="viewport" content="initial-scale=1.0, user-scalable=no" /> 
        <title>ViaGPS | <?=$cp->getSession()->get("accountName")?></title>
        <link rel="Shortcut Icon" href="favicon.ico"/>
        <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=true"></script>
        <script type="text/javascript" src="http://google-maps-utility-library-v3.googlecode.com/svn/tags/markermanager/1.0/src/markermanager.js"></script>
        <script type="text/javascript" src="http://google-maps-utility-library-v3.googlecode.com/svn/trunk/markerclusterer/src/markerclusterer.js"></script>
        <script src="js/jquery-1.7.min.js" type="text/javascript"></script>
        <script type="text/javascript" src="js/ui/jquery.ui.core.js"></script>
        <script type="text/javascript" src="js/ui/jquery.ui.widget.js"></script>
        <script type="text/javascript" src="js/ui/jquery.ui.mouse.js"></script>
        <script type="text/javascript" src="js/ui/jquery.ui.draggable.js"></script>
        <script src="js/jquery.url.js" type="text/javascript"></script>
        <script src="js/menuGMap.js" type="text/javascript"></script>
        <script src="js/jquery.validate.js" type="text/javascript"></script>
        <script src="js/jquery.dataTables.min.js" type="text/javascript"></script>
        <script src="js/jquery.titleBlink.js" type="text/javascript"></script>
        <script type="text/javascript" src="js/ui/jquery.ui.datepicker.js"></script>
        <script type="text/javascript" src="js/ui/i18n/jquery.ui.datepicker-es.js"></script>
        <script type="text/javascript" src="js/jquery.tmpl.min.js"></script>
        <script type="text/javascript" src="js/jquery.infieldlabel.min.js"></script>
        <script type="text/javascript" src="js/highcharts.js"></script>
        <script type="text/javascript" src="js/jquery.jgrowl_compressed.js"></script>
        <script type="text/javascript" src="js/list.js"></script>
        <script type="text/javascript" src="/js/jquery.jplayer.min.js"></script>
        <script src="js/jquery.tablesorter.min.js"></script>
        <script src="js/mon_alarma.js" type="text/javascript"></script>
        <script src="js/bootstrap.js" type="text/javascript"></script>
        <script src="js/main.js" type="text/javascript"></script>
        <link rel="stylesheet" type="text/css" href="css/jquery.jgrowl.css" />
        <link rel="stylesheet" type="text/css" href="css/bootstrap.css?26042012" />
        <link rel="stylesheet" type="text/css" href="css/viagps.css?26042012" />
        <script type="text/javascript">
            var _gaq = _gaq || [];
            _gaq.push(['_setAccount', 'UA-29049761-1']);
            _gaq.push(['_setDomainName', 'viagps.cl']);
            _gaq.push(['_setAllowHash', false]);
            _gaq.push(['_trackPageview']);

            (function() {
                var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
                ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
                var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
            })();
        </script>
    </head>
    <body>
        <div id="alarmaSound"></div>
        <div id="page-wrap">
            <div id="inside">
                <div class="navbar navbar-fixed-top">
                    <div class="navbar-inner">
                        <div class="container">
                            <a class="brand" href="http://www.viagps.cl" target="_blank"><img src="img/logo2.png" width="160" style="float: left;margin: -8px 10px 0 0px;"/></a>
                            <div class="nav-collapse">
                                <ul class="nav">
                                    <? if($cp->isAllow("monitoreo")) { ?>
                                        <li <?= ($cp->sec == "monitoreo") ? " class='active'" : ""; ?>><a href="?sec=monitoreo">Monitoreo</a></li>
                                    <? } ?>
                                    <? if($cp->isAllow("reporte")) { ?>
                                        <? if($cp->sec == "reporte") { ?>
                                            <li class="active"><a href="?sec=reporte&ssec=auditoria">Reportes</a></li>
                                        <? } else { ?>
                                            <li class="dropdown <?= ($cp->sec == "reporte") ? "active" : ""; ?>">
                                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Reportes <b class="caret"></b></a>
                                                <ul class="dropdown-menu">
                                                    <li><a href="/#/reporte/auditoria" onClick="setReporte(0);">Auditoria</a></li>
                                                    <li><a href="/#/reporte/alarma" onClick="setReporte(1);">Alarmas</a></li>
                                                    <li><a href="/#/reporte/recorrido" onClick="setReporte(2);">Km. Recorridos</a></li>
                                                    <li><a href="/#/reporte/velocidad" onClick="setReporte(3);">Velocidad</a></li>
                                                    <li><a href="/#/reporte/consumo" onClick="setReporte(4);">Consumo</a></li>
                                                </ul>
                                            </li>
                                        <? } ?>
                                    <? } ?>
                                    <? if($cp->isAllow("configuracion")) { ?>
                                        <? if($cp->sec == "configuracion") { ?>
                                            <li class="active"><a href="?sec=configuracion&ssec=vehiculo">Configuraci&oacute;n</a></li>
                                        <? } else { ?>
                                            <li class="dropdown">
                                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Configuraci&oacute;n <b class="caret"></b></a>
                                                <ul class="dropdown-menu">
                                                    <? if($cp->isAllow("configuracion", "vehiculo")) { ?><li><a href="?sec=configuracion&ssec=vehiculo">Veh&iacute;culos</a></li><? } ?>
                                                    <? if($cp->isAllow("configuracion", "conductor")) { ?><li><a href="?sec=configuracion&ssec=conductor">Conductores</a></li><? } ?>
                                                    <? if($cp->isAllow("configuracion", "usuario")) { ?><li><a href="?sec=configuracion&ssec=usuario">Usuarios</a></li><? } ?>
                                                    <? if($cp->isAllow("configuracion", "alarma")) { ?><li><a href="?sec=configuracion&ssec=alarma">Alarmas</a></li><? } ?>
                                                    <? if($cp->isAllow("configuracion", "puntointeres")) { ?><li><a href="?sec=configuracion&ssec=puntointeres">Ptos. Interes</a></li><? } ?>
                                                    <? if($cp->isAllow("configuracion", "geozona")) { ?><li><a href="?sec=configuracion&ssec=geozona">Geo Zona</a></li><? } ?>
                                                </ul>
                                            </li>
                                        <? } ?>
                                    <? } ?>
                                </ul>
                                <ul class="nav pull-right">
                                    <li class="dropdown">
                                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?= $cp->getSession()->get("user"); ?> <b class="caret"></b></a>
                                        <ul class="dropdown-menu">
                                            <li><a href="?sec=log&do=out">Cerrar sesi&oacute;n</a></li>
                                        </ul>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <? if($cp->sec == "configuracion") { ?>
                    <div class="subnav subnav-fixed">
                        <ul class="nav nav-pills">
                            <? if($cp->isAllow("configuracion", "vehiculo")) { ?><li <?= ($cp->getCSec()->sec == "vehiculo") ? " class='active'" : ""; ?>><a href="?sec=configuracion&ssec=vehiculo">Veh&iacute;culos</a></li><? } ?>
                            <? if($cp->isAllow("configuracion", "conductor")) { ?><li <?= ($cp->getCSec()->sec == "conductor") ? " class='active'" : ""; ?>><a href="?sec=configuracion&ssec=conductor">Conductores</a></li><? } ?>
                            <? if($cp->isAllow("configuracion", "usuario")) { ?><li <?= ($cp->getCSec()->sec == "usuario") ? " class='active'" : ""; ?>><a href="?sec=configuracion&ssec=usuario">Usuarios</a></li><? } ?>
                            <? if($cp->isAllow("configuracion", "alarma")) { ?><li <?= ($cp->getCSec()->sec == "alarma") ? " class='active'" : ""; ?>><a href="?sec=configuracion&ssec=alarma">Alarmas</a></li><? } ?>
                            <? if($cp->isAllow("configuracion", "puntointeres")) { ?><li <?= ($cp->getCSec()->sec == "puntointeres") ? " class='active'" : ""; ?>><a href="?sec=configuracion&ssec=puntointeres">Puntos de Inter&eacute;s</a></li><? } ?>
                            <? if($cp->isAllow("configuracion", "geozona")) { ?><li <?= ($cp->getCSec()->sec == "geozona") ? " class='active'" : ""; ?>><a href="?sec=configuracion&ssec=geozona">Geo Zona</a></li><? } ?>
                        </ul>
                    </div>
                <? } ?>
                <?if($cp->sec == "reporte") {?>
                    <div class="subnav subnav-fixed">
                        <ul class="nav nav-pills">
                            <li <?= ($cp->getCSec()->sec == "auditoria") ? " class='active'" : ""; ?>><a href="?sec=reporte&ssec=auditoria">Auditor&iacute;a</a></li>
                            <li <?= ($cp->getCSec()->sec == "alarma") ? " class='active'" : ""; ?>><a href="?sec=reporte&ssec=alarma">Alarmas</a></li>
    <!--                            <li <?= ($cp->getCSec()->sec == "detencion") ? " class='active'" : ""; ?>><a href="?sec=reporte&ssec=detencion">Detenciones</a></li>-->
                            <li <?= ($cp->getCSec()->sec == "recorrido") ? " class='active'" : ""; ?>><a href="?sec=reporte&ssec=recorrido">Kilometros recorridos</a></li>
    <!--                            <li <?= ($cp->getCSec()->sec == "sensor") ? " class='active'" : ""; ?>><a href="?sec=reporte&ssec=sensor">Sensores</a></li>-->
                            <li <?= ($cp->getCSec()->sec == "velocidad") ? " class='active'" : ""; ?>><a href="?sec=reporte&ssec=velocidad">Velocidad</a></li>
                            <li <?= ($cp->getCSec()->sec == "consumo") ? " class='active'" : ""; ?>><a href="?sec=reporte&ssec=consumo">Consumo</a></li>
                        </ul>
                    </div>
                <? } ?>
                <? if($cp->sec == "monitoreo") { ?>
                <div id="right-sidebar">
                    <div id="bar">
                        <h2>&Uacute;ltimas Alarmas</h2>
                        <div class="scroll">
                        <ul id="alarma"></ul>
                        </div>
                    </div>
                    <div id="toggle-right">><br />></div>
                </div>
                <? } ?>
                <? if($cp->sec == "monitoreo") { ?>
                <div id="left-sidebar">
                    <div id="toggle-left"><<br /><</div>
                    <div id="bar">
                        <div class="mon_botonera">
                            <a id="btn_pint" class="checkbox tp" onClick="showPInteres(); return false;" title="Mostrar puntos de interes"><i class="icon-map-marker"></i></a>
                            <a id="btn_buscar" class="checkbox tp" title="Buscar direcci&oacute;n"><i class="icon-search"></i></a>
                        </div>
                        <h2>Veh&iacute;culos</h2>
                        <div id="devices" class="jp-container">
<!--                            <label for="devFiltro">Buscar veh&iacute;culo</label><input class="search" id="devFiltro"/>-->
                            <form id="devFiltro">
                                <input type="text" class="search" name="sDev" value="" id="sDev" autocomplete="off" placeholder="Buscar Veh&iacute;culo"/>
                            </form>
                            <div class="scroll" style="margin-left: -10px;">
                                <ul class="grupo">
                                    <? foreach($cp->getCSec()->grupos as $g) { ?>
                                        <li><a href="#" class="nomGrupo"><span id="estado"><img src="img/collapse.png" border="0" class="imgEstado"/> </span><span><?=$g->displayName?></span></a>
                                            <div id="info">
                                                <? foreach($cp->getCSec()->sensor as $s) { ?>
                                                <? if($s->IN_TABLA == 1) { ?>
                                                <span title="<?=$s->NOM_SENSOR?>"><?=$s->ABR_SENSOR?></span>
                                                <? } ?>
                                                <? } ?>
                                                <span title="Velocidad">Vel</span>
                                            </div>
                                            <ul class="device list">
                                                <? $dev = $cp->getCSec()->getDeviceByGrupo($g->groupID) ?>
                                                <? foreach($dev as $d) { ?>
                                                    <li class="dev_<?=$d->deviceID?>" deviceID="<?=$d->deviceID?>"><span class="nomDevice"><?=$d->displayName?></span><span id="estado"></span>
                                                        <div id="info">
                                                            <? foreach($cp->getCSec()->sensor as $s) { ?>
                                                            <? if($s->IN_TABLA == 1) { ?>
                                                            <span id="S<?=$s->ID_SENSOR?>">
                                                                <img src='img/no_sensor.png' width='14' alt='No disponible' title='No instalado'/>
                                                            </span>
                                                            <? } ?>
                                                            <? } ?>
                                                            <span id="velocidad" class="tp">0</span>
                                                        </div>
                                                        <div class="clear"></div>
                                                    </li>
                                                <? } ?>
                                            </ul>
                                        </li>
                                    <? } ?>
                                </ul>
                            </div>
                        </div>
                        <div id="active_dev" style="display:none;" class="nivel_10">
                            <ul class="unstyled">
                                <li id="titulo"></li>
                                <li id="conductor"></li>
                                <li id="patente"></li>
                                <li id="velocidad"></li>
                                <? foreach($cp->getCSec()->sensor as $s) { ?>
                                <? if($s->IN_DETALLE == 1) { ?>
                                <li id="S<?=$s->ID_SENSOR?>"></li>
                                <? } ?>
                                <? } ?>
                                <li id="direccion"></li>
                                <li id="fecha"></li>
                            </ul>
                        </div>
                        <div id="tooltip" style="display:none;"></div>
                <? } ?> 
                    </div>
                </div>
                
                <div id="main-content">
                    <? include $cp->getCSec()->getLayout(); ?>
                </div>
<!--                fin main-content-->
                <div style="clear: both;"></div>
            </div>
<!--            fin inside-->
            <div style="clear: both;"></div>
        </div>
<!--        fin page-wrap-->
    </body>
</html>