<?
$error = array("", "El usuario NO existe", "La contrase&ntilde;a NO pudo ser enviada");
$tipoError = array("", "error", "error");
if(isset($_GET["e"])) {
    $msg = $error[$_GET["e"]];
    $tipoMsg = $tipoError[$_GET["e"]];
} else {
    $msg = "Ingrese su usuario para recuperar la contrase&ntilde;a";
    $tipoMsg = "information";
}
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1" />
        <title>Mantenedor JNR | Entrar</title>
        <link rel="stylesheet" href="css/mantenedor.css" type="text/css" media="screen" />
<!--        <link rel="stylesheet" href="css/reset.css" type="text/css" media="screen" />
        <link rel="stylesheet" href="css/style.css" type="text/css" media="screen" />
        <link rel="stylesheet" href="css/invalid.css" type="text/css" media="screen" />-->
        <script type="text/javascript" src="js/jquery-1.4.2.min.js"></script>
        <script type="text/javascript" src="js/jquery.wysiwyg.js"></script>
        <script src="js/jquery.validate.js" type="text/javascript"></script>
        <script type="text/javascript" src="js/todo.js"></script>
    </head>
    <body>
        <div id="contenedor" class="png_bg">
            <div id="header">
                <div id="swf"></div>
            </div>
            <div id="main">
                <div class="ingreso">
                    <div id="ingresar">
                        <img src="img/recuperar-tit.gif" />
                        <div class="notification <?= $tipoMsg ?> png_bg">
                            <div><?= $msg ?></div>
                        </div>
                        <form action="?sec=log&do=rec" method="POST" id="formu">
                            <table width="400" border="0" cellspacing="0" cellpadding="5">
                                <tr>
                                    <td width="122">Usuario</td>
                                    <td width="258"><input class="text-input small-input required" type="text" name="user"></input</td>
                                </tr>
                            </table>
                            <div align="center">
                                <input class="button" type="image" value="Entrar" src="img/recuperar.gif"/>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <div id="clear"></div>
            <div id="footer">
                <div align="center">JNR Propiedades | Huechuraba<br />
                    Avda. Pedro Fontova  7789  L.10  Tel.  (56 - 2)  248 84 95  -  09-089 87 38
                </div>
            </div>
        </div>
    </body>
<!--    <body id="login">
        <div id="wrapper" class="png_bg">
            <div id="top">
                <img id="logo" src="img/header.jpg" alt="Simpla Admin logo" />
            </div>  End #logn-top 
            <div id="content">
                <h2>Recuperar contrase&ntilde;a</h2>
                <div id="login">
                    <form action="?sec=log&do=rec" method="POST" id="formu">
                        <div class="notification <?=$tipoMsg?> png_bg">
                            <div><?=$msg?></div>
                        </div>
                        <p>
                            <label>Usuario:</label>
                            <input class="text-input required" type="text" name="user"></input>
                        </p>
                        <div class="clear"></div>
                        <p>
                                                <button type='submit'>Entrar</button>
                            <input class="button" type="submit" value="Recuperar" />
                        </p>
                        <div class="clear"></div>
                    </form>
                </div>
            </div>
            <div id="footer">
                <p>Jaime Nieto Rosas Propiedades - Av. Pedro Fontova 7789 - Local 10 - Huechuraba</p>
            </div>
        </div>
    </body>-->
</html>