<?
$error = array("", "Usuario o contrase&ntilde;a incorrectos", "La contrase&ntilde;a fue enviada correctamente");
$tipoError = array("", "error", "success");
if (isset($_GET["e"])) {
    $msg = $error[$_GET["e"]];
    $tipoMsg = $tipoError[$_GET["e"]];
} else {
    $msg = "Complete los siguientes campos para ingresar";
    $tipoMsg = "information";
}
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1" />
        <title>GPSLine | Entrar</title>
        <script type="text/javascript" src="js/jquery-1.4.2.min.js"></script>
        <script src="js/jquery.validate.js" type="text/javascript"></script>
        <script type="text/javascript" src="js/login.js"></script>
        <link rel="stylesheet" type="text/css" href="css/reset.css" />
        <link rel="stylesheet" type="text/css" href="css/login.css" />
        <script type="text/javascript">
          var _gaq = _gaq || [];
          _gaq.push(['_setAccount', 'UA-22276420-1']);
          _gaq.push(['_setDomainName', '.gpsline.cl']);
          _gaq.push(['_trackPageview']);

          (function() {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
          })();
        </script>
    </head>
    <body>
        <div id="contenedor">
            <div id="contenido">
                <div class="logo" align="center"><img src="img/logo.png" border="0" alt="" title="" /></div>
                <form action="?sec=log&do=in" method="post" id="formu">
                    <div class="notification <?=$tipoMsg;?> png_bg">
                        <div><?=$msg;?></div>
                    </div>
                    <p>
                        <label>Usuario:</label>
                        <input class="text-input medium-input required" type="text" name="user" value=""/>
                    </p>
                    <div class="clear"></div>
                    <p>
                        <label>Contrase&ntilde;a:</label>
                        <input class="text-input medium-input required" type="password" name="pass" value=""/>
                    </p>
                    <div class="clear"></div>
                    <p>
                        <input class="button" type="submit" value="Entrar" />
                    </p>
                    <div class="clear"></div>
                </form>
            </div>
            <p align="center">GPSLINE / San Juan #4693, San Joaqu&iacute;n - Santiago - Chile / <br />Tel&eacute;fono (+56 2) 424 78 80 <br />&copy; 2010 GPSLINE - Reservados todos los derechos / Desarrollo: NETMARKET</p>
        </div>
    </body>
</html>