<?
$error = array("", "Usuario o contrase&ntilde;a incorrectos", "La contrase&ntilde;a fue enviada correctamente");
$tipoError = array("", "error", "success");
if (isset($_GET["e"])) {
    $msg = $error[$_GET["e"]];
    $tipoMsg = $tipoError[$_GET["e"]];
} else {
    $msg = "Complete los siguientes campos para ingresar";
    $tipoMsg = "information";
}
?>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>ViaGPS | Bienvenido</title>
        <script src="js/jquery-1.7.min.js" type="text/javascript"></script>
        <script src="js/jquery.validate.js" type="text/javascript"></script>
        <script type="text/javascript" src="js/login.js"></script>
        <link rel="stylesheet" type="text/css" href="css/bootstrap.css" />
        <link rel="stylesheet" type="text/css" href="css/login.css" />
        <script type="text/javascript">
            var _gaq = _gaq || [];
            _gaq.push(['_setAccount', 'UA-29049761-1']);
            _gaq.push(['_setDomainName', 'viagps.cl']);
            _gaq.push(['_trackPageview']);

            (function() {
                var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
                ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
                var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
            })();
        </script>
    </head>
    <body>
        <div id="contenedor">
            <div id="contenido">
                <div class="logo" align="center"><img src="img/logo_home2.png" border="0" alt="" title="" /></div>
                <form action="?sec=log&do=in" method="post" id="formu" class="">
                    <div class="control-group">
<!--                        <label>Usuario:</label>-->
                        <div class="controls">
                            <input class="required" type="text" name="user" value="" placeholder="Usuario"/>
                        </div>
                    </div>
                    <div class="control-group">
<!--                        <label>Contrase&ntilde;a:</label>-->
                        <div class="controls">
                            <input class="required" type="password" name="pass" value="" placeholder="Contrase&ntilde;a"/>
                        </div>
                    </div>
                    <div class="control-group">
                        <div class="controls">
                            <p id="msg">&nbsp;</p>
                            <input class="btn btn-primary btn-large" id="btn" type="submit" value="Entrar" style="width: 235px;"/>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </body>
</html>