<?php ?>
<script src="js/geozona.js" type="text/javascript"></script>
<div  class="container" style="padding-top:80px;">
    <div class="page-header">
        <h1>Puntos de Inter&eacute;s</h1>
        <a href="?sec=configuracion&ssec=puntointeres&op=add" class="btn pull-right"><i class="icon-plus"></i>Agregar Punto de interes</a>
    </div>
    <div class="bloque">
<!--        <h2>Todos</h2>-->
        <? if(count($cp->getCSec()->getCSec()->puntos)>0) { ?>
        <table class="table table-striped table-bordered" id="lista">
            <thead>
                <tr>
                    <th class="red">Nombre</th>
                    <th class="red">Direcci&oacute;n</th>
                    <th class="actionCol">Acci&oacute;n</th>
                </tr>
            </thead>
            <tbody>
            <? foreach ($cp->getCSec()->getCSec()->puntos as $p) { ?>
                <tr <?=(!$p->estado_pinteres)?"class='deleted'":""?>>
                    <td><?= $p->name; ?></td>
                    <td><?= $p->address; ?></td>
                    <td class="actionCol">
                        <a href="?sec=configuracion&ssec=puntointeres&op=mod&id=<?= $p->id; ?>" class="tp" title="Editar"><i class="icon-edit"></i></a>
                        <a href="?sec=configuracion&ssec=puntointeres&do=del&id=<?= $p->id; ?>" class="tp" title="Eliminar"><i class="icon-remove"></i></a>
                    </td>
                </tr>
            <? } ?>
            <tbody>
        </table>
        <? } else {?>
        <p class="mensaje">No hay puntos de inter&eacute;s</p>
        <? } ?>
    </div>
</div>

