<?
function getSelect($obj, $val, $id, $nom, $sel = null, $style=null, $onChange=null) {
    $r = "<SELECT name='$nom' class='medium-input' style='$style' onChange=\"" . $onChange . "\" id='$nom'>";
    $r .= "<OPTION value = '-1' DISABLED>Seleccionar...</OPTION>";
    foreach ($obj as $o) {
        if ($sel == $o->$id) {
            $r .= "<OPTION value='" . $o->$id . "' SELECTED>" . $o->$val . "</OPTION>";
        } else {
            $r .= "<OPTION value='" . $o->$id . "'>" . $o->$val . "</OPTION>";
        }
    }
    $r .= "</SELECT>";
    return $r;
}
$error = array("Los cambios fueron guardados correctamente", "Los cambios NO pudieron ser guardados");
if(isset($_GET["e"])) {
    $msg = $error[$_GET["e"]];
    if($_GET["e"]>0) {
        $tipoMsg = "error";
    } else {
        $tipoMsg = "success";
    }
} else {
    if($cp->getCSec()->getCSec()->op == "add") {
        $msg = "Complete los siguientes campos";
        $tipoMsg = "info";
    } else {
        $msg = "Edite los campos que quiera modificar";
        $tipoMsg = "info";
    }
}
?>
<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
<!--<script type="text/javascript" src="http://maps.google.com/maps/api/js?libraries=geometry&sensor=false"></script>-->
<!--<link rel="stylesheet" type="text/css" href="css/form.css" />-->
<link rel="stylesheet" type="text/css" href="css/menuGMap.css" />
<link rel="stylesheet" type="text/css" href="css/punto_interes.css" />
<!--<script src="js/polygonEdit_packed.js" type="text/javascript"></script>-->
<!--<script src="js/polylineEdit_packed.js" type="text/javascript"></script>-->
<script src="js/menuGMap.js" type="text/javascript"></script>
<script src="js/punto_interes_form.js" type="text/javascript"></script>
<div class="center_content">
    <div id="top-nav">
        <ul>
            <li><a href="?sec=configuracion&ssec=puntointeres">Volver</a></li>
        </ul>
    </div>
    <h1>Puntos de inter&eacute;s</h1>
    <div class="bloque">
    <h2><?= $cp->getCSec()->getCSec()->tilSec; ?></h2>
    <div id="geo-main">
        <div id="map"></div>
        <form name="poly" method="post" action="?sec=configuracion&ssec=puntointeres&do=<?=$cp->getCSec()->getCSec()->op;?>" id="formu">
            <div class="alert-message <?=$tipoMsg;?>">
                <p><?=$msg;?></p>
            </div>
            <div class="clearfix">
                <label>Nombre:</label>
                <div class="input">
                <input class="required span5" type="text" name="nom" value="<?=($cp->getCSec()->getCSec()->obj!=null)?$cp->getCSec()->getCSec()->obj->name:""?>"/>
                <input type="hidden" name="accountID" value="<?=($cp->getCSec()->getCSec()->obj==null)?$cp->getSession()->get("accountID"):$cp->getCSec()->getCSec()->obj->accountid?>"/>
                <input type="hidden" name="id" value="<?=($cp->getCSec()->getCSec()->obj!=null)?$cp->getCSec()->getCSec()->obj->id:""?>"/>
                </div>
            </div>
            <div class="clearfix">
                <label>Direcci&oacute;n:</label>
                <div class="input">
                <input class="required span5" type="text" name="dir" id="dir" value="<?=($cp->getCSec()->getCSec()->obj!=null)?$cp->getCSec()->getCSec()->obj->address:""?>"/>
<!--                <input type="hidden" name="lat" value="<?=($cp->getCSec()->getCSec()->obj!=null)?$cp->getCSec()->getCSec()->obj->latitude:""?>"/>
                <input type="hidden" name="lon" value="<?=($cp->getCSec()->getCSec()->obj!=null)?$cp->getCSec()->getCSec()->obj->longitude:""?>"/>-->
                <a onclick="geoLocaliza(); return false;" title="Ubicar en el mapa"><img src="img/marker.png" height="26" border="0"/></a>
                </div>
            </div>
            <div class="clearfix">
                <label>Latitud:</label>
                <div class="input">
                <input class="required span2" type="text" name="lat" value="<?=($cp->getCSec()->getCSec()->obj!=null)?$cp->getCSec()->getCSec()->obj->latitude:""?>"/>
                </div>
            </div>
            <div class="clearfix">
                <label>Longitud:</label>
                <div class="input">
                <input class="required span2" type="text" name="lon" value="<?=($cp->getCSec()->getCSec()->obj!=null)?$cp->getCSec()->getCSec()->obj->longitude:""?>"/>
                </div>
            </div>
            <div class="clearfix">
                <label>Radio:
                </label>
                <div class="input">
                <input class="span2 required" type="text" name="rad" id="rad"  value="<?=($cp->getCSec()->getCSec()->obj!=null)?$cp->getCSec()->getCSec()->obj->radio:"50"?>"/>
                <span class="help-inline">en metros</span>
                </div>
            </div>
            <div class="clearfix">
            <label>Estado:</label>
                <div class="input">
                <?=getSelect($cp->getCSec()->getCSec()->estados, "estado", "id", "estado", ($cp->getCSec()->getCSec()->obj!=null)?$cp->getCSec()->getCSec()->obj->estado_pinteres:"");?>
                </div>
            </div>
            <div class="clearfix">
                <div class="input">
                <input class="btn danger" type="submit" value="Guardar" />
                </div>
            </div>
        </form>
        <div class="clear"></div>
    </div>
    </div>
</div>