<?php ?>
<script src="js/geozona.js" type="text/javascript"></script>
<div class="center_content">        
    <h1>Puntos de Inter&eacute;s</h1>
    <div id="local-nav"><a href="?sec=configuracion&ssec=puntointeres&op=add" class="btn"><img src="img/add.png" border="0"/>Agregar Punto de interes</a></div>
    <div class="bloque">
<!--        <h2>Todos</h2>-->
        <? if(count($cp->getCSec()->getCSec()->puntos)>0) { ?>
        <table class="zebra-striped" id="lista">
            <thead>
                <tr>
                    <th class="red">Nombre</th>
                    <th class="red">Direcci&oacute;n</th>
                    <th class="actionCol">Editar</th>
                    <th class="actionCol">Eliminar</th>
                </tr>
            </thead>
            <tbody>
            <? foreach ($cp->getCSec()->getCSec()->puntos as $p) { ?>
                <tr <?=(!$p->estado_pinteres)?"class='deleted'":""?>>
                    <td><?= $p->name; ?></td>
                    <td><?= $p->address; ?></td>
                    <td class="actionCol"><a href="?sec=configuracion&ssec=puntointeres&op=mod&id=<?= $p->id; ?>"><img src="img/page_edit.png" border="0" /></a></td>
                    <td class="actionCol"><a href="?sec=configuracion&ssec=puntointeres&do=del&id=<?= $p->id; ?>"><img src="img/delete.png" border="0" /></a></td>
                </tr>
            <? } ?>
            <tbody>
        </table>
        <? } else {?>
        <p class="mensaje">No hay puntos de inter&eacute;s</p>
        <? } ?>
    </div>
</div>

