<?php
function getSelect($arr, $til, $nom, $id, $onChange=null) {
    $sel = "<SELECT name='$til' id='$til' onChange=\"$onChange\" class='txt'>";
    $sel .= "<OPTION disabled value=0 selected>$til</OPTION>";
    foreach ($arr as $a) {
        $sel .= "<OPTION value='" . $a->$id . "'>" . $a->$nom . "</OPTION>";
    }
    $sel .= "</SELECT>";
//    echo $sel;
    return $sel;
}

function getTime($arr, $nom) {
    $sel = "<SELECT name='$nom' id='$nom' class='time'>";
    foreach($arr as $a) {
        if($a<10) {
            $sel .= "<OPTION value='$a'>0".$a."</OPTION>";
        } else {
            $sel .= "<OPTION value='$a'>".$a."</OPTION>";
        }
    }
    $sel .= "</SELECT>";
    return $sel;
}
?>
<link type="text/css" href="css/cal_chico.css" rel="stylesheet" />
<!--<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
<link rel="stylesheet" href="js/fancybox/jquery.fancybox-1.3.4.css" type="text/css" media="screen" />
<script type="text/javascript" src="js/fancybox/jquery.fancybox-1.3.4.pack.js"></script>
<script type="text/javascript" src="js/ui/jquery.ui.core.js"></script>
<script type="text/javascript" src="js/ui/jquery.ui.widget.js"></script>
<script type="text/javascript" src="js/ui/jquery.ui.datepicker.js"></script>
<script type="text/javascript" src="js/ui/i18n/jquery.ui.datepicker-es.js"></script>
<script type="text/javascript" src="js/ui/jquery-ui-1.8.4.custom.js"></script>
<script type="text/javascript" src="js/jquery-ui-timepicker-addon.js"></script>-->

<script src="js/reporte_2.js" type="text/javascript"></script>

<script id="fila_0" type="text/html">
    <tr id="${i}"><td align="center">${fecha}</td><td>${distancia}</td><td>${velocidad}</td></tr>
</script>
<script id="fila_1" type="text/x-jquery-tmpl">
    <tr id="${i}"><td align="center">${fecha}</td><td>${displayName}</td><td>${licensePlate}</td><td>${alarma}</td><td>{{html regla}}</td></tr>
</script>
<script id="fila_3" type="text/html">
    <tr id="${i}"><td align="center">${fecha}</td><td>${displayName}</td><td>${licensePlate}</td><td>${velocidad}</td></tr>
</script>
<? if(!isset($_GET["ajax"])) { ?>
<div class="center_content">
<? } ?>
    <h1><?=(isset($_GET["ajax"]))?"Reportes > ":""?><?=htmlentities($cp->getCSec()->tilSec)?></h1>
    <div class="mon_botonera">
        <a id="btn_down" class="checkbox tooltip" title="Descargar reporte"><img src="img/save.png" height="20"/></a>
<!--        <a id="btn_print" class="checkbox tooltip" onClick="showPInteres(); return false;" title="Imprimir reporte"><img src="img/print.png" height="20"/></a>-->
        <a id="btn_pint" class="checkbox tooltip" onClick="showPInteres(); return false;" title="Mostrar puntos de interes"><img src="img/marker.png" height="20"/></a>
    </div>
    <div id="filtros">
        <form name="alerta" method="post" id="formu" action="?sec=reporte&ssec=<?=$cp->getCSec()->sec?>&get=reporte" class="<?=(isset($_GET["ajax"]))?"side":"inline"?>">
            <div style="<?=(isset($_GET["ajax"]))?"margin-bottom: 5px;":"display:inline-block; margin-bottom: 5px;"?>"><label>Inicio: </label>
                <input type="text" name="ini" value="" class="text-input required fecha" id="fecha_ini" readonly/>@
                <?=getTime($cp->getCSec()->getCSec()->hrs, "hrs_ini");?>:
                <?=getTime($cp->getCSec()->getCSec()->min, "min_ini");?>
            </div>
            <div style="<?=(isset($_GET["ajax"]))?"margin-bottom: 5px;":"display:inline-block; margin-bottom: 5px;"?>"><label>Fin: </label>
                <input type="text" name="fin" value="" class="text-input required fecha" id="fecha_fin" readonly/>@
                <?=getTime($cp->getCSec()->getCSec()->hrs, "hrs_fin");?>:
                <?=getTime($cp->getCSec()->getCSec()->min, "min_fin");?>
            </div>
            <div style="<?=(isset($_GET["ajax"]))?"margin-bottom: 5px;":"display:inline-block; margin-bottom: 5px;"?>"><label>Grupo: </label><?= getSelect($cp->getCSec()->getCSec()->grupos, "Grupo", "displayName", "groupID", "getDevices(this, 'Vehiculo');"); ?></div>
            <div style="<?=(isset($_GET["ajax"]))?"margin-bottom: 5px;":"display:inline-block; margin-bottom: 5px;"?>"><label>Vehiculo: </label><?= getSelect($cp->getCSec()->getCSec()->devices, "Vehiculo", "licensePlate", "deviceID"); ?></div>
            <? if($cp->getCSec()->sec == "velocidad") { ?>
                <div style="<?=(isset($_GET["ajax"]))?"margin-bottom: 5px;":"display:inline-block; margin-bottom: 5px;"?>">
                    <label>Velocidad: </label><?=getSelect($cp->getCSec()->getCSec()->ope, "Operador", "nom", "id");?>:
                    <input type="text" name="vel" value="" class="text-input small required" id="vel"/>
                </div>
            <? } ?>
            <input type="submit" value="Generar" class="button" id="submit"/>
<!--            <div class="mon_botonera">
                <a id="btn_pint" class="checkbox tooltip" onClick="showPInteres(); return false;" title="Descargar reporte"><img src="img/save.png" height="20"/></a>
                <a id="btn_pint" class="checkbox tooltip" onClick="showPInteres(); return false;" title="Imprimir reporte"><img src="img/print.png" height="20"/></a>
            </div>-->
        </form>
    </div>
    <div class="<?=(!isset($_GET["ajax"]))?"bloque":""?>" id="reporte">
        <p class="mensaje">Complete los campos para generar el reporte</p>
    </div>
<? if(!isset($_GET["ajax"])) { ?>
    </div>
<? } ?>