<?php
?>
<script src="js/usuario.js" type="text/javascript"></script>
<div  class="container" style="padding-top:80px;">
    <div class="page-header">
        <h1>Usuarios</h1>
        <a href="?sec=configuracion&ssec=usuario&op=add" class="btn pull-right"><i class="icon-plus"></i>Agregar Usuario</a>
    </div>
    <div class="bloque">
<!--        <h2>Todos</h2>-->
        <table class="table table-striped table-bordered" id="lista">
            <thead>
                <tr>
                    <th class="red">Usuario</th>
                    <th class="red">Nombre completo</th>
                    <th class="red">Tipo</th>
                    <th class="red">E-mail</th>
                    <th class="actionCol">Acci&oacute;n</th>
                </tr>
            </thead>
            <tbody>
                <? foreach($cp->getCSec()->getCSec()->usuarios as $a) {?>
                <tr <?=(!$a->isActive)?"class='deleted'":""?>>
                    <td><?= $a->userName; ?></td>
                    <td><?= $a->contactName; ?></td>
                    <td><?= $a->displayName; ?></td>
                    <td><?= $a->contactEmail; ?></td>
                    <td class="actionCol">
                        <a href="?sec=configuracion&ssec=usuario&op=mod&id=<?=$a->userID;?>" class="tp" title="Editar"><i class="icon-edit"></i></a>
                        <a href="?sec=configuracion&ssec=usuario&do=del&id=<?=$a->userID;?>" class="tp" data-original-title="Eliminar"><i class="icon-remove"></i></a>
                </tr>
                <? } ?>
            <tbody>
        </table>
    </div>
</div>