<?php
function getSelect($obj, $val, $id, $nom, $sel=null, $onChange=null) {
    $r = "<SELECT name='$nom' id='$nom' onChange=\"".$onChange."\" class='chzn-select span3'>";
    foreach($obj as $o) {
        if($sel!=null && $o->$id==$sel) {
            $r .= "<OPTION value='".trim($o->$id)."' selected>".utf8_encode($o->$val)."</OPTION>";
        } else {
            $r .= "<OPTION value='".trim($o->$id)."'>".utf8_encode($o->$val)."</OPTION>";
        }
    }
    $r .= "</SELECT>";
    return $r;
}

function getRadio($obj, $val, $id, $nom, $sel=null) {
    $r = "<div class='btn-group' data-toggle='buttons-radio' name='$nom'>";
    foreach($obj as $o) {
        if($sel!=null && $o->$id==$sel) {
            $r .= "<button class='btn active' value='".trim($o->$id)."'>".utf8_encode($o->$val)."</button>";
        } else {
            $r .= "<button class='btn' value='".trim($o->$id)."'>".utf8_encode($o->$val)."</button>";
        }
    }
    $r .= "</div>";
    $r .= "<input type='hidden' name='$nom' value='$sel' />";
    return $r;
}

function getCheck($obj, $val, $id, $nom, $sel=null) {
    $r = "<div class='btn-group' data-toggle='buttons-checkbox' name='$nom'>";
    $h = "";
    foreach($obj as $o) {
        if($sel!=null && $o->$sel) {
            $r .= "<button name='".$nom."_".$o->$id."' class='btn active' value='1'>".utf8_encode($o->$val)."</button>";
            $h .= "<input type='hidden' name='".$nom."_".$o->$id."' value='1' />";
        } else {
            $r .= "<button name='".$nom."_".$o->$id."' class='btn' value='1'>".utf8_encode($o->$val)."</button>";
            $h .= "<input type='hidden' name='".$nom."_".$o->$id."' value='0' />";
        }
    }
    $r .= "</div>";
    $r .= $h;
    return $r;
}

$error = array("Los cambios fueron guardados correctamente", "Los cambios NO pudieron ser guardados", "El usuario NO pudo ser creado");
if(isset($_GET["e"])) {
    $msg = $error[$_GET["e"]];
    if($_GET["e"]>0) {
        $tipoMsg = "error";
    } else {
        $tipoMsg = "success";
    }
} else {
    if($cp->getCSec()->getCSec()->op == "add") {
        $msg = "<strong>Complete</strong> los siguientes campos";
        $tipoMsg = "info";
    } else {
        $msg = "<strong>Edite</strong> los campos que quiera modificar";
        $tipoMsg = "info";
    }
}
?>
<link rel="stylesheet" href="css/chosen.css" type="text/css" />
<script type="text/javascript" src="js/chosen.jquery.min.js"></script>
<script src="js/usuario_form.js" type="text/javascript"></script>
<div  class="container" style="padding-top:80px;">
    <div class="page-header">
        <h1>Usuarios</h1>
        <a href="?sec=configuracion&ssec=usuario" class="btn pull-right"><i class="icon-arrow-left"></i>Volver</a>
    </div>
    <h2><?=$cp->getCSec()->getCSec()->tilSec?></h2>
    <div class="alert-message <?=$tipoMsg;?> png_bg">
        <p><?=$msg;?></p>
    </div>
    <div class="well">
    <form action="?sec=configuracion&ssec=usuario&do=<?=$cp->getCSec()->getCSec()->op?>" method="post" name="formu" id="formu" class="form-horizontal">
        <div class="control-group">
            <label class="control-label" for="user">Usuario:</label>
            <div class="controls">
            <input id="user" class="text-input medium-input required" type="text" name="user" value="<?=($cp->getCSec()->getCSec()->obj!=null)?$cp->getCSec()->getCSec()->obj->userName:""?>" <?=($cp->getCSec()->getCSec()->obj!=null)?"DISABLED":""?>/>
            <input type="hidden" name="id" value="<?=($cp->getCSec()->getCSec()->obj!=null)?$cp->getCSec()->getCSec()->obj->userID:""?>" id="userID"/>
            <input type="hidden" name="accountID" value="<?=$cp->getSession()->get("accountID")?>"/>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="pass">Contrase&ntilde;a:</label>
            <div class="controls">
            <input class="text-input medium-input <?=($cp->getCSec()->getCSec()->obj!=null)?"":"required"?>" type="password" name="pass" value="" id="pass"/>
            <?if($cp->getCSec()->getCSec()->obj!=null) {?><span class="help-inline">Solo si desea cambiarla</span><? } ?>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="nom">Nombre Completo:</label>
            <div class="controls">
            <input id="nom" class="text-input medium-input required" type="text" name="nom" value="<?=($cp->getCSec()->getCSec()->obj!=null)?$cp->getCSec()->getCSec()->obj->contactName:""?>"/>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="ema">E-mail:</label>
            <div class="controls">
            <input id="ema" class="text-input medium-input required" type="text" name="ema" value="<?=($cp->getCSec()->getCSec()->obj!=null)?$cp->getCSec()->getCSec()->obj->contactEmail:""?>"/>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="rol">Tipo de usuario:</label>
            <div class="controls">
            <?=getRadio($cp->getCSec()->getCSec()->roles, "DisplayName", "roleID", "rol", ($cp->getCSec()->getCSec()->obj!=null)?$cp->getCSec()->getCSec()->obj->roleID:"2");?>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="estado">Estado:</label>
            <div class="controls">
            <?=getRadio($cp->getCSec()->getCSec()->estados, "estado", "id", "estado", ($cp->getCSec()->getCSec()->obj!=null)?$cp->getCSec()->getCSec()->obj->isActive:"1");?>
            </div>
        </div>
        <? if($cp->getCSec()->getCSec()->op == "mod" && ($cp->getCSec()->getCSec()->obj->roleID == 2 || $cp->getCSec()->getCSec()->obj->roleID == 3)) { ?>
        <div class="control-group">
            <label class="control-label" for="grupo">Grupos de vehiculos:</label>
            <div class="controls">
            <?=getSelect($cp->getCSec()->getCSec()->grupos, "displayName", "groupID", "grupo");?>
            <a onClick="addUserGrupo(); return false;" style="cursor:pointer;" class="btn"><i class="icon-plus-sign"></i>Asignar</a>
            </div>
        </div>
        <div class="control-group">
            <div class="controls">
<!--                <div class="span4" id="<?=$gr->groupListID?>" style="position:relative; margin-left: 0;">-->
                <ul class="span4 unstyled" id="grupos">
                <? foreach($cp->getCSec()->getCSec()->userGr as $gr) { ?>
                    <li id="<?=$gr->groupListID?>" style="position:relative; padding: 5px; border-left: 2px solid #ccc; margin-bottom: 4px;">
                        <a href="?sec=configuracion&ssec=vehiculo&op=mod_grupo&id=<?=$gr->groupID?>"><?=$gr->displayName?></a><a onClick="delUserGrupo(<?=$gr->groupListID?>); return false;" style="cursor:pointer; position: absolute; right: 0;"><i class="icon-remove-sign"></i></a>
                    </li>
                <? } ?>
                </ul>
<!--                </div>-->
            </div>
        </div>
        <? } ?>
        <div class="control-group">
            <div class="controls">
            <input class="btn btn-primary" type="submit" value="Guardar" />
            </div>
        </div>
    </form>
    </div>
</div>