<?php
?>
<script src="http://maps.google.com/maps/api/js?sensor=true" type="text/javascript"></script>
<script src="js/jquery.jeditable.js" type="text/javascript"></script>
<script src="js/vehiculos.js" type="text/javascript"></script>
<div class="center_content">
    <h1>Veh&iacute;culos y Grupos</h1>
    <div id="local-nav"><a href="?sec=configuracion&ssec=vehiculo&op=add_grupo" class="btn"><img src="img/add.png" border="0"/>Agregar Grupo</a></div>
    <div class="bloque">
        <h2>Grupos</h2>
        <? if(count($cp->getCSec()->getCSec()->grupos)>0) { ?>
        <table class="zebra-striped" id="grupos">
            <thead>
                <tr>
                    <th class="red">Nombre</th>
                    <th class="red">Descripci&oacute;n</th>
                    <th class="red">N&deg; Veh&iacute;culos</th>
                    <th class="actionCol {sorter: false}">Editar</th>
                    <th class="actionCol {sorter: false}">Eliminar</th>
                </tr>
            </thead>
            <tbody>
                <? foreach($cp->getCSec()->getCSec()->grupos as $a) {?>
                <tr <?=(!$a->isActive)?"class='deleted'":""?>>
                    <td align="center"><?= $a->displayName; ?></td>
                    <td><?= $a->description; ?></td>
                    <td align="center"><?= $cp->getCSec()->getCSec()->getNumDevice($a->groupID)->TOTAL; ?></td>
                    <td class="actionCol"><a href="?sec=configuracion&ssec=vehiculo&op=mod_grupo&id=<?=$a->groupID;?>"><img src="img/page_edit.png" border="0" /></a></td>
                    <td class="actionCol"><a href="?sec=configuracion&ssec=vehiculo&do=del_grupo&id=<?=$a->groupID;?>"><img src="img/delete.png" border="0" /></a></td>
                </tr>
                <? } ?>
            <tbody>
<!--                Miguel Angel Centeno-->
<!--                3395427-->
<!--                985274394-->
        </table>
        <? } else { ?>
            <p class="mensaje">No hay grupos</p>
        <? } ?>
    </div>
    <div class="bloque">
        <h2>Veh&iacute;culos</h2>
        <? if(count($cp->getCSec()->getCSec()->device)>0) { ?>
        <table class="zebra-striped" id="vehiculos">
            <thead>
                <tr>
                    <th class="red">Nombre a mostrar</th>
                    <th class="red">Patente</th>
                    <th class="red">Conductor</th>
<!--                    <th align="center" width="100">IMEI</th>-->
                    <th class="red">&Uacute;ltima posici&oacute;n</th>
                    <th class="red">Fecha</th>
<!--                    <th align="center" width="40">Editar</th>
                    <th align="center" width="40">Eliminar</th>-->
                </tr>
            </thead>
            <tbody>
                <? $i=0; ?>
                <? foreach($cp->getCSec()->getCSec()->device as $a) {?>
                <tr>
                    <td class="editable medium"><span class="edit" id="<?=$a->deviceID;?>"><?= $a->displayName; ?></span></td>
                    <td align="center"><?= $a->licensePlate; ?></td>
                    <td class="editable select"><span class="driveEdit edit" id="dr_<?=$a->driverID?>" devID="<?=$a->deviceID;?>"><?= $cp->getCSec()->getCSec()->condSel[$a->driverID] ?></span></td>
<!--                    <td align="center"><?= $a->imeiNumber; ?></td>-->
                    <td class="posicion" id="pos_<?=$i?>"><?= $a->latitude.",".$a->longitude; ?></td>
                    <td align="center"><?= $a->fecha ?></td>
<!--                    <td align="center"><a href="?sec=vehiculo&op=mod&id=<?=$a->deviceID;?>"><img src="img/page_edit.png" border="0" /></a></td>
                    <td align="center"><a href="?sec=vehiculo&op=del&id=<?=$a->deviceID;?>"><img src="img/delete.png" border="0" /></a></td>-->
                </tr>
                <? $i++; ?>
                <? } ?>
            </tbody>
        </table>
        <? } else { ?>
        <p class="mensaje">No hay veh&iacute;culos</p>
        <? } ?>
    </div>
</div>
<script>
    $(".driveEdit").editable(function(value, settings){
        console.log(this);
        dri = $(this);
        json = $.parseJSON(settings.data);
        if(dri.attr("id") != "dr_"+value) {
            $.ajax({
                url: "?sec=configuracion&ssec=vehiculo&do=modConductor&idDri="+value+"&idDev="+dri.attr("devID"),
                type: "get",
                beforeSend: function(){
                },
                complete: function(data) {
                }
            });
            if(value!="0") {
                $old = $("#dr_"+value);
                $old.html("Sin conductor");
                $old.attr("id", "dr_0");
            }
            dri.attr("id", "dr_"+value);
            return json[value];
        } else {
            console.log("el mismo");
            return json[value];
        }
    },
    {
        data   : '<?php print json_encode($cp->getCSec()->getCSec()->condSel); ?>',
        type: 'select',
        submit: 'Ok',
        indicator : 'Guardando...',
        tooltip: 'Click para editar',
        cssclass: "inline-form"
//        onblur: 'ignore'
    }
    );
</script>